AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template for a VPC containing public and private EC2 Instances

########################################################################

Parameters:
  VPC:
    Type: String
    Description: VPC.
    Default: 'vpc-2e48bf48'
    
  #Application Tier
  LatestAmiId:
    Description: Gets the latest AMI from Systems Manager Parameter store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  TestInstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.nano
      - t3.medium
      - t3.large
    ConstraintDescription: must be a valid EC2 instance type.

  TestInstanceKeyName:
    Description: Name of an existing EC2 KeyPair for SSH access to the instnace
    Type: AWS::EC2::KeyPair::KeyName
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: can contain only ASCII characters.

Resources:

  ###########
  # Relay Node - Public
  ###########

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupName: 'MySG'
      GroupDescription: >-
        Enable for specific ports to/from allowed PUBLIC CIDR
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'

  TestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref TestInstanceType
      KeyName: !Ref TestInstanceKeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: PublicSecurityGroup

########################################################################

Outputs:
  RelayNodePrivateDNS:
    Value: !GetAtt TestInstance.PrivateDnsName
  
########################################################################
# Metadata is used to group and order how the CloudFormation parameters are
# displayed when you deploy the template using the AWS Console
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "EC2 configuration"
        Parameters:
          - testInstanceType
          - testInstanceKeyName